// AUTO-GENERATED from dataset/universities.compiled.json by scripts/build-global-countries.mjs
// Do not edit by hand — regenerate with: node scripts/build-global-countries.mjs

export type RegionName =
  | "Europe"
  | "Asia"
  | "Middle East"
  | "North America"
  | "South America"
  | "Africa"
  | "Oceania"

export type GlobalCountry = {
  /** Canonical dataset country name — used as the quiz selection id. */
  id: string
  /** Friendly name shown to students. */
  name: string
  region: RegionName
  /** All names under which this country appears in universities.compiled.json. */
  datasetCountries: string[]
  /** One of the 16 priority destinations with full destination-page data. */
  core: boolean
  /** Annual budget starting point in INR (core destinations only). */
  minBudgetInr: number | null
}

export const REGIONS: RegionName[] = [
  "Europe",
  "Asia",
  "Middle East",
  "North America",
  "South America",
  "Africa",
  "Oceania",
]

export const GLOBAL_COUNTRIES: GlobalCountry[] = [
  {
    id: "Afghanistan",
    name: "Afghanistan",
    region: "Asia",
    datasetCountries: ["Afghanistan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Albania",
    name: "Albania",
    region: "Europe",
    datasetCountries: ["Albania"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Algeria",
    name: "Algeria",
    region: "Africa",
    datasetCountries: ["Algeria"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Andorra",
    name: "Andorra",
    region: "Europe",
    datasetCountries: ["Andorra"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Angola",
    name: "Angola",
    region: "Africa",
    datasetCountries: ["Angola"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Antigua and Barbuda",
    name: "Antigua and Barbuda",
    region: "North America",
    datasetCountries: ["Antigua and Barbuda"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Argentina",
    name: "Argentina",
    region: "South America",
    datasetCountries: ["Argentina"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Armenia",
    name: "Armenia",
    region: "Asia",
    datasetCountries: ["Armenia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Australia",
    name: "Australia",
    region: "Oceania",
    datasetCountries: ["Australia"],
    core: true,
    minBudgetInr: 1870000,
  },
  {
    id: "Austria",
    name: "Austria",
    region: "Europe",
    datasetCountries: ["Austria"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Azerbaijan",
    name: "Azerbaijan",
    region: "Asia",
    datasetCountries: ["Azerbaijan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Bahamas",
    name: "Bahamas",
    region: "North America",
    datasetCountries: ["Bahamas"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Bahrain",
    name: "Bahrain",
    region: "Middle East",
    datasetCountries: ["Bahrain"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Bangladesh",
    name: "Bangladesh",
    region: "Asia",
    datasetCountries: ["Bangladesh"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Barbados",
    name: "Barbados",
    region: "North America",
    datasetCountries: ["Barbados"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Belarus",
    name: "Belarus",
    region: "Europe",
    datasetCountries: ["Belarus"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Belgium",
    name: "Belgium",
    region: "Europe",
    datasetCountries: ["Belgium"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Belize",
    name: "Belize",
    region: "North America",
    datasetCountries: ["Belize"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Benin",
    name: "Benin",
    region: "Africa",
    datasetCountries: ["Benin"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Bermuda",
    name: "Bermuda",
    region: "North America",
    datasetCountries: ["Bermuda"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Bhutan",
    name: "Bhutan",
    region: "Asia",
    datasetCountries: ["Bhutan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Bolivia, Plurinational State of",
    name: "Bolivia",
    region: "South America",
    datasetCountries: ["Bolivia, Plurinational State of"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Bosnia and Herzegovina",
    name: "Bosnia and Herzegovina",
    region: "Europe",
    datasetCountries: ["Bosnia and Herzegovina"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Botswana",
    name: "Botswana",
    region: "Africa",
    datasetCountries: ["Botswana"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Brazil",
    name: "Brazil",
    region: "South America",
    datasetCountries: ["Brazil"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Virgin Islands, British",
    name: "British Virgin Islands",
    region: "North America",
    datasetCountries: ["Virgin Islands, British"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Brunei Darussalam",
    name: "Brunei",
    region: "Asia",
    datasetCountries: ["Brunei Darussalam"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Bulgaria",
    name: "Bulgaria",
    region: "Europe",
    datasetCountries: ["Bulgaria"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Burkina Faso",
    name: "Burkina Faso",
    region: "Africa",
    datasetCountries: ["Burkina Faso"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Burundi",
    name: "Burundi",
    region: "Africa",
    datasetCountries: ["Burundi"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Cambodia",
    name: "Cambodia",
    region: "Asia",
    datasetCountries: ["Cambodia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Cameroon",
    name: "Cameroon",
    region: "Africa",
    datasetCountries: ["Cameroon"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Canada",
    name: "Canada",
    region: "North America",
    datasetCountries: ["Canada"],
    core: true,
    minBudgetInr: 1700000,
  },
  {
    id: "Cape Verde",
    name: "Cape Verde",
    region: "Africa",
    datasetCountries: ["Cape Verde"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Cayman Islands",
    name: "Cayman Islands",
    region: "North America",
    datasetCountries: ["Cayman Islands"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Central African Republic",
    name: "Central African Republic",
    region: "Africa",
    datasetCountries: ["Central African Republic"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Chad",
    name: "Chad",
    region: "Africa",
    datasetCountries: ["Chad"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Chile",
    name: "Chile",
    region: "South America",
    datasetCountries: ["Chile"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "China",
    name: "China",
    region: "Asia",
    datasetCountries: ["China"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Colombia",
    name: "Colombia",
    region: "South America",
    datasetCountries: ["Colombia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Congo",
    name: "Congo",
    region: "Africa",
    datasetCountries: ["Congo"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Costa Rica",
    name: "Costa Rica",
    region: "North America",
    datasetCountries: ["Costa Rica"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Côte d'Ivoire",
    name: "Côte d'Ivoire",
    region: "Africa",
    datasetCountries: ["Côte d'Ivoire"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Croatia",
    name: "Croatia",
    region: "Europe",
    datasetCountries: ["Croatia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Cuba",
    name: "Cuba",
    region: "North America",
    datasetCountries: ["Cuba"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Cyprus",
    name: "Cyprus",
    region: "Europe",
    datasetCountries: ["Cyprus"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Czech Republic",
    name: "Czech Republic",
    region: "Europe",
    datasetCountries: ["Czech Republic"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Denmark",
    name: "Denmark",
    region: "Europe",
    datasetCountries: ["Denmark"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Djibouti",
    name: "Djibouti",
    region: "Africa",
    datasetCountries: ["Djibouti"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Dominica",
    name: "Dominica",
    region: "North America",
    datasetCountries: ["Dominica"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Dominican Republic",
    name: "Dominican Republic",
    region: "North America",
    datasetCountries: ["Dominican Republic"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Congo, the Democratic Republic of the",
    name: "DR Congo",
    region: "Africa",
    datasetCountries: ["Congo, the Democratic Republic of the"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Ecuador",
    name: "Ecuador",
    region: "South America",
    datasetCountries: ["Ecuador"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Egypt",
    name: "Egypt",
    region: "Africa",
    datasetCountries: ["Egypt"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "El Salvador",
    name: "El Salvador",
    region: "North America",
    datasetCountries: ["El Salvador"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Equatorial Guinea",
    name: "Equatorial Guinea",
    region: "Africa",
    datasetCountries: ["Equatorial Guinea"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Eritrea",
    name: "Eritrea",
    region: "Africa",
    datasetCountries: ["Eritrea"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Estonia",
    name: "Estonia",
    region: "Europe",
    datasetCountries: ["Estonia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Swaziland",
    name: "Eswatini",
    region: "Africa",
    datasetCountries: ["Swaziland"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Ethiopia",
    name: "Ethiopia",
    region: "Africa",
    datasetCountries: ["Ethiopia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Faroe Islands",
    name: "Faroe Islands",
    region: "Europe",
    datasetCountries: ["Faroe Islands"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Fiji",
    name: "Fiji",
    region: "Oceania",
    datasetCountries: ["Fiji"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Finland",
    name: "Finland",
    region: "Europe",
    datasetCountries: ["Finland"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "France",
    name: "France",
    region: "Europe",
    datasetCountries: ["France"],
    core: true,
    minBudgetInr: 1020000,
  },
  {
    id: "French Guiana",
    name: "French Guiana",
    region: "South America",
    datasetCountries: ["French Guiana"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "French Polynesia",
    name: "French Polynesia",
    region: "Oceania",
    datasetCountries: ["French Polynesia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Gabon",
    name: "Gabon",
    region: "Africa",
    datasetCountries: ["Gabon"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Gambia",
    name: "Gambia",
    region: "Africa",
    datasetCountries: ["Gambia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Georgia",
    name: "Georgia",
    region: "Asia",
    datasetCountries: ["Georgia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Germany",
    name: "Germany",
    region: "Europe",
    datasetCountries: ["Germany"],
    core: true,
    minBudgetInr: 680000,
  },
  {
    id: "Ghana",
    name: "Ghana",
    region: "Africa",
    datasetCountries: ["Ghana"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Greece",
    name: "Greece",
    region: "Europe",
    datasetCountries: ["Greece"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Greenland",
    name: "Greenland",
    region: "North America",
    datasetCountries: ["Greenland"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Grenada",
    name: "Grenada",
    region: "North America",
    datasetCountries: ["Grenada"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Guadeloupe",
    name: "Guadeloupe",
    region: "North America",
    datasetCountries: ["Guadeloupe"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Guam",
    name: "Guam",
    region: "Oceania",
    datasetCountries: ["Guam"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Guatemala",
    name: "Guatemala",
    region: "North America",
    datasetCountries: ["Guatemala"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Guinea",
    name: "Guinea",
    region: "Africa",
    datasetCountries: ["Guinea"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Guyana",
    name: "Guyana",
    region: "South America",
    datasetCountries: ["Guyana"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Haiti",
    name: "Haiti",
    region: "North America",
    datasetCountries: ["Haiti"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Honduras",
    name: "Honduras",
    region: "North America",
    datasetCountries: ["Honduras"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Hong Kong",
    name: "Hong Kong",
    region: "Asia",
    datasetCountries: ["Hong Kong"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Hungary",
    name: "Hungary",
    region: "Europe",
    datasetCountries: ["Hungary"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Iceland",
    name: "Iceland",
    region: "Europe",
    datasetCountries: ["Iceland"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Indonesia",
    name: "Indonesia",
    region: "Asia",
    datasetCountries: ["Indonesia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Iran",
    name: "Iran",
    region: "Middle East",
    datasetCountries: ["Iran"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Iraq",
    name: "Iraq",
    region: "Middle East",
    datasetCountries: ["Iraq"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Ireland",
    name: "Ireland",
    region: "Europe",
    datasetCountries: ["Ireland"],
    core: true,
    minBudgetInr: 1530000,
  },
  {
    id: "Israel",
    name: "Israel",
    region: "Middle East",
    datasetCountries: ["Israel"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Italy",
    name: "Italy",
    region: "Europe",
    datasetCountries: ["Italy"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Jamaica",
    name: "Jamaica",
    region: "North America",
    datasetCountries: ["Jamaica"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Japan",
    name: "Japan",
    region: "Asia",
    datasetCountries: ["Japan"],
    core: true,
    minBudgetInr: 1020000,
  },
  {
    id: "Jordan",
    name: "Jordan",
    region: "Middle East",
    datasetCountries: ["Jordan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Kazakhstan",
    name: "Kazakhstan",
    region: "Asia",
    datasetCountries: ["Kazakhstan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Kenya",
    name: "Kenya",
    region: "Africa",
    datasetCountries: ["Kenya"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Kosovo",
    name: "Kosovo",
    region: "Europe",
    datasetCountries: ["Kosovo"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Kuwait",
    name: "Kuwait",
    region: "Middle East",
    datasetCountries: ["Kuwait"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Kyrgyzstan",
    name: "Kyrgyzstan",
    region: "Asia",
    datasetCountries: ["Kyrgyzstan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Lao People's Democratic Republic",
    name: "Laos",
    region: "Asia",
    datasetCountries: ["Lao People's Democratic Republic"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Latvia",
    name: "Latvia",
    region: "Europe",
    datasetCountries: ["Latvia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Lebanon",
    name: "Lebanon",
    region: "Middle East",
    datasetCountries: ["Lebanon"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Lesotho",
    name: "Lesotho",
    region: "Africa",
    datasetCountries: ["Lesotho"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Liberia",
    name: "Liberia",
    region: "Africa",
    datasetCountries: ["Liberia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Libya",
    name: "Libya",
    region: "Africa",
    datasetCountries: ["Libya"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Liechtenstein",
    name: "Liechtenstein",
    region: "Europe",
    datasetCountries: ["Liechtenstein"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Lithuania",
    name: "Lithuania",
    region: "Europe",
    datasetCountries: ["Lithuania"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Luxembourg",
    name: "Luxembourg",
    region: "Europe",
    datasetCountries: ["Luxembourg"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Macao",
    name: "Macau",
    region: "Asia",
    datasetCountries: ["Macao"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Madagascar",
    name: "Madagascar",
    region: "Africa",
    datasetCountries: ["Madagascar"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Malawi",
    name: "Malawi",
    region: "Africa",
    datasetCountries: ["Malawi"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Malaysia",
    name: "Malaysia",
    region: "Asia",
    datasetCountries: ["Malaysia"],
    core: true,
    minBudgetInr: 680000,
  },
  {
    id: "Maldives",
    name: "Maldives",
    region: "Asia",
    datasetCountries: ["Maldives"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Mali",
    name: "Mali",
    region: "Africa",
    datasetCountries: ["Mali"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Malta",
    name: "Malta",
    region: "Europe",
    datasetCountries: ["Malta"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Mauritania",
    name: "Mauritania",
    region: "Africa",
    datasetCountries: ["Mauritania"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Mauritius",
    name: "Mauritius",
    region: "Africa",
    datasetCountries: ["Mauritius"],
    core: true,
    minBudgetInr: 595000,
  },
  {
    id: "Mexico",
    name: "Mexico",
    region: "North America",
    datasetCountries: ["Mexico"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Moldova, Republic of",
    name: "Moldova",
    region: "Europe",
    datasetCountries: ["Moldova, Republic of"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Mongolia",
    name: "Mongolia",
    region: "Asia",
    datasetCountries: ["Mongolia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Montenegro",
    name: "Montenegro",
    region: "Europe",
    datasetCountries: ["Montenegro"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Montserrat",
    name: "Montserrat",
    region: "North America",
    datasetCountries: ["Montserrat"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Morocco",
    name: "Morocco",
    region: "Africa",
    datasetCountries: ["Morocco"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Mozambique",
    name: "Mozambique",
    region: "Africa",
    datasetCountries: ["Mozambique"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Myanmar",
    name: "Myanmar",
    region: "Asia",
    datasetCountries: ["Myanmar"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Namibia",
    name: "Namibia",
    region: "Africa",
    datasetCountries: ["Namibia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Nepal",
    name: "Nepal",
    region: "Asia",
    datasetCountries: ["Nepal"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Netherlands",
    name: "Netherlands",
    region: "Europe",
    datasetCountries: ["Netherlands"],
    core: true,
    minBudgetInr: 1360000,
  },
  {
    id: "New Caledonia",
    name: "New Caledonia",
    region: "Oceania",
    datasetCountries: ["New Caledonia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "New Zealand",
    name: "New Zealand",
    region: "Oceania",
    datasetCountries: ["New Zealand"],
    core: true,
    minBudgetInr: 1530000,
  },
  {
    id: "Nicaragua",
    name: "Nicaragua",
    region: "North America",
    datasetCountries: ["Nicaragua"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Niger",
    name: "Niger",
    region: "Africa",
    datasetCountries: ["Niger"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Nigeria",
    name: "Nigeria",
    region: "Africa",
    datasetCountries: ["Nigeria"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Niue",
    name: "Niue",
    region: "Oceania",
    datasetCountries: ["Niue"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Korea, Democratic People's Republic of",
    name: "North Korea",
    region: "Asia",
    datasetCountries: ["Korea, Democratic People's Republic of"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "North Macedonia",
    name: "North Macedonia",
    region: "Europe",
    datasetCountries: ["North Macedonia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Norway",
    name: "Norway",
    region: "Europe",
    datasetCountries: ["Norway"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Oman",
    name: "Oman",
    region: "Middle East",
    datasetCountries: ["Oman"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Pakistan",
    name: "Pakistan",
    region: "Asia",
    datasetCountries: ["Pakistan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Palestine, State of",
    name: "Palestine",
    region: "Middle East",
    datasetCountries: ["Palestine, State of"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Panama",
    name: "Panama",
    region: "North America",
    datasetCountries: ["Panama"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Papua New Guinea",
    name: "Papua New Guinea",
    region: "Oceania",
    datasetCountries: ["Papua New Guinea"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Paraguay",
    name: "Paraguay",
    region: "South America",
    datasetCountries: ["Paraguay"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Peru",
    name: "Peru",
    region: "South America",
    datasetCountries: ["Peru"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Philippines",
    name: "Philippines",
    region: "Asia",
    datasetCountries: ["Philippines"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Poland",
    name: "Poland",
    region: "Europe",
    datasetCountries: ["Poland"],
    core: true,
    minBudgetInr: 850000,
  },
  {
    id: "Portugal",
    name: "Portugal",
    region: "Europe",
    datasetCountries: ["Portugal"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Puerto Rico",
    name: "Puerto Rico",
    region: "North America",
    datasetCountries: ["Puerto Rico"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Qatar",
    name: "Qatar",
    region: "Middle East",
    datasetCountries: ["Qatar"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Réunion",
    name: "Réunion",
    region: "Africa",
    datasetCountries: ["Réunion"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Romania",
    name: "Romania",
    region: "Europe",
    datasetCountries: ["Romania"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Russian Federation",
    name: "Russia",
    region: "Europe",
    datasetCountries: ["Russian Federation"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Rwanda",
    name: "Rwanda",
    region: "Africa",
    datasetCountries: ["Rwanda"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Saint Kitts and Nevis",
    name: "Saint Kitts and Nevis",
    region: "North America",
    datasetCountries: ["Saint Kitts and Nevis"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Saint Lucia",
    name: "Saint Lucia",
    region: "North America",
    datasetCountries: ["Saint Lucia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Saint Vincent and the Grenadines",
    name: "Saint Vincent and the Grenadines",
    region: "North America",
    datasetCountries: ["Saint Vincent and the Grenadines"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Samoa",
    name: "Samoa",
    region: "Oceania",
    datasetCountries: ["Samoa"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "San Marino",
    name: "San Marino",
    region: "Europe",
    datasetCountries: ["San Marino"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Saudi Arabia",
    name: "Saudi Arabia",
    region: "Middle East",
    datasetCountries: ["Saudi Arabia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Senegal",
    name: "Senegal",
    region: "Africa",
    datasetCountries: ["Senegal"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Serbia",
    name: "Serbia",
    region: "Europe",
    datasetCountries: ["Serbia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Seychelles",
    name: "Seychelles",
    region: "Africa",
    datasetCountries: ["Seychelles"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Sierra Leone",
    name: "Sierra Leone",
    region: "Africa",
    datasetCountries: ["Sierra Leone"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Singapore",
    name: "Singapore",
    region: "Asia",
    datasetCountries: ["Singapore"],
    core: true,
    minBudgetInr: 2125000,
  },
  {
    id: "Slovakia",
    name: "Slovakia",
    region: "Europe",
    datasetCountries: ["Slovakia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Slovenia",
    name: "Slovenia",
    region: "Europe",
    datasetCountries: ["Slovenia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Somalia",
    name: "Somalia",
    region: "Africa",
    datasetCountries: ["Somalia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "South Africa",
    name: "South Africa",
    region: "Africa",
    datasetCountries: ["South Africa"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Korea, Republic of",
    name: "South Korea",
    region: "Asia",
    datasetCountries: ["Korea, Republic of"],
    core: true,
    minBudgetInr: 1190000,
  },
  {
    id: "South Sudan",
    name: "South Sudan",
    region: "Africa",
    datasetCountries: ["South Sudan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Spain",
    name: "Spain",
    region: "Europe",
    datasetCountries: ["Spain"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Sri Lanka",
    name: "Sri Lanka",
    region: "Asia",
    datasetCountries: ["Sri Lanka"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Sudan",
    name: "Sudan",
    region: "Africa",
    datasetCountries: ["Sudan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Suriname",
    name: "Suriname",
    region: "South America",
    datasetCountries: ["Suriname"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Sweden",
    name: "Sweden",
    region: "Europe",
    datasetCountries: ["Sweden"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Switzerland",
    name: "Switzerland",
    region: "Europe",
    datasetCountries: ["Switzerland"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Syrian Arab Republic",
    name: "Syria",
    region: "Middle East",
    datasetCountries: ["Syrian Arab Republic"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Taiwan, Province of China",
    name: "Taiwan",
    region: "Asia",
    datasetCountries: ["Taiwan, Province of China"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Tajikistan",
    name: "Tajikistan",
    region: "Asia",
    datasetCountries: ["Tajikistan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Tanzania, United Republic of",
    name: "Tanzania",
    region: "Africa",
    datasetCountries: ["Tanzania, United Republic of"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Thailand",
    name: "Thailand",
    region: "Asia",
    datasetCountries: ["Thailand"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Togo",
    name: "Togo",
    region: "Africa",
    datasetCountries: ["Togo"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Trinidad and Tobago",
    name: "Trinidad and Tobago",
    region: "North America",
    datasetCountries: ["Trinidad and Tobago"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Tunisia",
    name: "Tunisia",
    region: "Africa",
    datasetCountries: ["Tunisia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Turkiye",
    name: "Turkey",
    region: "Middle East",
    datasetCountries: ["Turkiye"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Turkmenistan",
    name: "Turkmenistan",
    region: "Asia",
    datasetCountries: ["Turkmenistan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Turks and Caicos Islands",
    name: "Turks and Caicos Islands",
    region: "North America",
    datasetCountries: ["Turks and Caicos Islands"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Uganda",
    name: "Uganda",
    region: "Africa",
    datasetCountries: ["Uganda"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Ukraine",
    name: "Ukraine",
    region: "Europe",
    datasetCountries: ["Ukraine"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "United Arab Emirates",
    name: "United Arab Emirates",
    region: "Middle East",
    datasetCountries: ["United Arab Emirates"],
    core: true,
    minBudgetInr: 1700000,
  },
  {
    id: "United Kingdom",
    name: "United Kingdom",
    region: "Europe",
    datasetCountries: ["United Kingdom"],
    core: true,
    minBudgetInr: 2125000,
  },
  {
    id: "United States",
    name: "United States",
    region: "North America",
    datasetCountries: ["United States"],
    core: true,
    minBudgetInr: 2380000,
  },
  {
    id: "Uruguay",
    name: "Uruguay",
    region: "South America",
    datasetCountries: ["Uruguay"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Uzbekistan",
    name: "Uzbekistan",
    region: "Asia",
    datasetCountries: ["Uzbekistan"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Holy See (Vatican City State)",
    name: "Vatican City",
    region: "Europe",
    datasetCountries: ["Holy See (Vatican City State)"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Venezuela, Bolivarian Republic of",
    name: "Venezuela",
    region: "South America",
    datasetCountries: ["Venezuela, Bolivarian Republic of"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Vietnam",
    name: "Vietnam",
    region: "Asia",
    datasetCountries: ["Viet Nam","Vietnam"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Yemen",
    name: "Yemen",
    region: "Middle East",
    datasetCountries: ["Yemen"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Zambia",
    name: "Zambia",
    region: "Africa",
    datasetCountries: ["Zambia"],
    core: false,
    minBudgetInr: null,
  },
  {
    id: "Zimbabwe",
    name: "Zimbabwe",
    region: "Africa",
    datasetCountries: ["Zimbabwe"],
    core: false,
    minBudgetInr: null,
  },
]

export const COUNTRY_BY_ID = new Map(GLOBAL_COUNTRIES.map((c) => [c.id, c]))

export const CORE_COUNTRY_IDS = new Set(GLOBAL_COUNTRIES.filter((c) => c.core).map((c) => c.id))

export type StateOption = {
  id: string
  label: string
}

/** State/province-level options shown for countries where it is relevant to studying there. */
export const STATE_OPTIONS: Record<string, StateOption[]> = {
  "United States": [
    { id: "Alabama", label: "Alabama" },
    { id: "Alaska", label: "Alaska" },
    { id: "Arizona", label: "Arizona" },
    { id: "Arkansas", label: "Arkansas" },
    { id: "California", label: "California" },
    { id: "Colorado", label: "Colorado" },
    { id: "Connecticut", label: "Connecticut" },
    { id: "Delaware", label: "Delaware" },
    { id: "District of Columbia", label: "District of Columbia" },
    { id: "Florida", label: "Florida" },
    { id: "Georgia", label: "Georgia" },
    { id: "Hawaii", label: "Hawaii" },
    { id: "Idaho", label: "Idaho" },
    { id: "Illinois", label: "Illinois" },
    { id: "Indiana", label: "Indiana" },
    { id: "Iowa", label: "Iowa" },
    { id: "Kansas", label: "Kansas" },
    { id: "Kentucky", label: "Kentucky" },
    { id: "Louisiana", label: "Louisiana" },
    { id: "Maine", label: "Maine" },
    { id: "Maryland", label: "Maryland" },
    { id: "Massachusetts", label: "Massachusetts" },
    { id: "Michigan", label: "Michigan" },
    { id: "Minnesota", label: "Minnesota" },
    { id: "Mississippi", label: "Mississippi" },
    { id: "Missouri", label: "Missouri" },
    { id: "Montana", label: "Montana" },
    { id: "Nebraska", label: "Nebraska" },
    { id: "Nevada", label: "Nevada" },
    { id: "New Hampshire", label: "New Hampshire" },
    { id: "New Jersey", label: "New Jersey" },
    { id: "New Mexico", label: "New Mexico" },
    { id: "New York", label: "New York" },
    { id: "North Carolina", label: "North Carolina" },
    { id: "North Dakota", label: "North Dakota" },
    { id: "Ohio", label: "Ohio" },
    { id: "Oklahoma", label: "Oklahoma" },
    { id: "Oregon", label: "Oregon" },
    { id: "Pennsylvania", label: "Pennsylvania" },
    { id: "Rhode Island", label: "Rhode Island" },
    { id: "South Carolina", label: "South Carolina" },
    { id: "South Dakota", label: "South Dakota" },
    { id: "Tennessee", label: "Tennessee" },
    { id: "Texas", label: "Texas" },
    { id: "Utah", label: "Utah" },
    { id: "Vermont", label: "Vermont" },
    { id: "Virginia", label: "Virginia" },
    { id: "Washington", label: "Washington" },
    { id: "West Virginia", label: "West Virginia" },
    { id: "Wisconsin", label: "Wisconsin" },
    { id: "Wyoming", label: "Wyoming" },
  ],
  Canada: [
    { id: "Alberta", label: "Alberta" },
    { id: "British Columbia", label: "British Columbia" },
    { id: "Manitoba", label: "Manitoba" },
    { id: "New Brunswick", label: "New Brunswick" },
    { id: "Newfoundland and Labrador", label: "Newfoundland and Labrador" },
    { id: "Northwest Territories", label: "Northwest Territories" },
    { id: "Nova Scotia", label: "Nova Scotia" },
    { id: "Nunavut", label: "Nunavut" },
    { id: "Ontario", label: "Ontario" },
    { id: "Prince Edward Island", label: "Prince Edward Island" },
    { id: "Quebec", label: "Quebec" },
    { id: "Saskatchewan", label: "Saskatchewan" },
    { id: "Yukon", label: "Yukon" },
  ],
  Australia: [
    { id: "Australian Capital Territory", label: "Australian Capital Territory" },
    { id: "New South Wales", label: "New South Wales" },
    { id: "Northern Territory", label: "Northern Territory" },
    { id: "Queensland", label: "Queensland" },
    { id: "South Australia", label: "South Australia" },
    { id: "Tasmania", label: "Tasmania" },
    { id: "Victoria", label: "Victoria" },
    { id: "Western Australia", label: "Western Australia" },
  ],
}

export const STATE_OPTION_COUNTRIES = Object.keys(STATE_OPTIONS)
